name: CI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        include:
          # iOS tests - Commented out until iOS targets are enabled
          # - target: iosSimulatorArm64Test
          #   os: macos-latest
          - target: desktopTest
            os: ubuntu-latest
          - target: testDebugUnitTest
            os: ubuntu-latest
          - target: testReleaseUnitTest
            os: ubuntu-latest
          - target: jsTest
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Validate Gradle Wrapper
      uses: gradle/actions/wrapper-validation@v3
      
    - name: Cache Kotlin Konan
      uses: actions/cache@v4
      with:
        path: |
          ~/.konan
        key: ${{ runner.os }}-${{ hashFiles('**/.lock') }}
        
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'
        
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v3
      with:
        arguments: ${{ matrix.target }} 