name: Publish to Maven Central

on:
  release:
    types: [released, prereleased]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: true
        default: '0.0.8'

permissions:
  contents: read

jobs:
  publish:
    name: Release build and publish
    runs-on: macos-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
      
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          ~/.konan
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Update version if manual dispatch
      if: github.event_name == 'workflow_dispatch'
      run: |
        VERSION="${{ github.event.inputs.version }}"
        echo "Publishing version: $VERSION"
        sed -i.bak "s/version = \".*\"/version = \"$VERSION\"/" responsive-ui/build.gradle.kts
        rm responsive-ui/build.gradle.kts.bak
        
    - name: Build and Test
      run: ./gradlew :responsive-ui:build --no-daemon --stacktrace
      env:
        GRADLE_OPTS: -Dorg.gradle.daemon=false
        
    - name: Debug Signing Configuration
      run: ./gradlew :responsive-ui:debugSigning --no-daemon
      env:
        ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
        ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
        ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
        ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
        ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY_CONTENTS }}
        GRADLE_OPTS: -Dorg.gradle.daemon=false
        
    - name: Publish to MavenCentral
      run: ./gradlew :responsive-ui:publishAllPublicationsToMavenCentralRepository --no-daemon --stacktrace
      env:
        ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
        ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
        ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
        ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
        ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY_CONTENTS }}
        GRADLE_OPTS: -Dorg.gradle.daemon=false
        
    - name: Create Release Notes
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}